blueprint:
  name: Reboot Unifi Devices
  description: >-
    Reboots selected Unifi Devices one after another
  domain: script
  input:
    unifi_devices:
      name: Unifi Device Restart Button
      description: Unifi Device Restart Button
      selector:
        entity:
          integration: unifi
          domain: button
          multiple: true

variables:
  unifi_devices: !input unifi_devices

sequence:
  - repeat:
      for_each: "{{ unifi_devices }}"
      sequence:
        - service: button.press
          target:
            entity_id: "{{ repeat.item }}"
        - delay:
            hours: 0
            minutes: 15
            seconds: 0
            milliseconds: 0
