blueprint:
  name: Send Telegram Camera Picture
  description: >-
    Sends an Camera Picture to a defined Telegram group
  domain: script
  input:
    camera_device:
      name: Camera Device
      description: Camera Device
      selector:
        entity:
          domain:
          - camera
          multiple: false

mode: queued
sequence:
  - variables:
      camera: !input camera_device
      camera_name: '{{ states[camera].name }}'
      file_name: >-
        {{ camera_name }}_{{ now ().year }}_{{ now ().month }}_{{ now ().day
        }}_{{ now ().hour }}_{{ now ().minute }}.jpg
  - service: camera.snapshot
    metadata: {}
    data:
      filename: /media/snapshots/{{ file_name }}
    target:
      entity_id: !input camera_device
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - action: telegram_bot.send_photo
    data:
      verify_ssl: true
      config_entry_id: 01JZCJFGV30T7XGAW3S1AWW2SF
      target:
        - -19909211
      file: /media/snapshots/{{ file_name }}
      caption: {{ camera_name }}
